name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
        image: mcr.microsoft.com/playwright:v1.56.1-jammy
    steps:
      - name: Check repository
        uses: actions/checkout@v4
      - name: Say hello
        run: echo hello
      - name: Run tests
        run: |

          echo "1. Verificando cabecera del archivo..."
          # Esto nos dirá si el archivo empieza con 'ELF' (que es lo correcto)
          head -c 4 ./shopping-store-linux-amd64
          
          echo -e "\n2. Intentando ejecución directa..."
          # Usamos 'sh' para intentar forzar la ejecución si el shell tiene dudas
          chmod +x ./shopping-store-linux-amd64
          ./shopping-store-linux-amd64 &

          echo "Wait for the ci to run"
          sleep 10
          echo "Install dependencies from lockfile"
          npm ci
          echo "verifying the port is working"
          curl -I http://localhost:2221
          echo "Run playwright tests"
          npm run test:ci
